export const developers = [
  {
    name: 'Igor Borovyk',
    role: 'Team Lead',
    image: new URL('../images/users/user-1.jpg', import.meta.url),
    github: 'https://github.com/SMAILe3001',

    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
  {
    name: 'Inna Nurbaeva',
    role: 'Scrum Master',
    image: new URL('../images/users/user-2.jpg', import.meta.url),
    github: 'https://github.com/InaUA',
    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
  {
    name: 'Stanislav Pravdiuk',
    role: 'Full Stack Developer',
    image: new URL('../images/users/user-3.jpg', import.meta.url),
    github: 'https://github.com/stanislav-pravdiuk',
    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
  {
    name: 'Konstantin Le',
    role: 'Full Stack Developer',
    image: new URL('../images/users/user-4.jpg', import.meta.url),
    github: 'https://github.com/klav28',
    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
  {
    name: 'Oleksii Kryventsov',
    role: 'Full Stack Developer',
    image: new URL('../images/users/user-5.jpg', import.meta.url),
    github: 'https://github.com/Oleksii-Kryventsov',
    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
  {
    name: 'Danylo Melnyk',
    role: 'Full Stack Developer',
    image: new URL('../images/users/user-6.jpg', import.meta.url),
    github: 'https://github.com/danjkamelnik',
    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
  {
    name: 'Bogdan Potopnyk',
    role: 'Full Stack Developer',
    image: new URL('../images/users/user-7.jpg', import.meta.url),
    github: 'https://github.com/Potopnyk',
    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
  {
    name: 'Oleksandr Kokhno',
    role: 'Full Stack Developer',
    image: new URL('../images/users/user-8.jpg', import.meta.url),
    github: 'https://github.com/Oleksandr-77',
    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
  {
    name: 'Oleksandr Pavlenko',
    role: 'Full Stack Developer',
    image: new URL('../images/users/user-9.jpg', import.meta.url),
    github: 'https://github.com/Oleksandr-Pavlenko1988',
    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
  {
    name: 'Ivan Kotov',
    role: 'Full Stack Developer',
    image: new URL('../images/users/user-10.jpg', import.meta.url),
    github: 'https://github.com/BubblePenguin',
    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
  {
    name: 'Dmytro Lysytsia',
    role: 'Full Stack Developer',
    image: new URL('../images/users/user-11.jpg', import.meta.url),
    github: 'https://github.com/Mr-Foxx',
    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
];
